### ISSUE TITLE
No support for Sound library on ARM devices (Raspberry Pi)

### ISSUE THREAD

**Issue by walkerdanny** [processing/processing-sound-archive#86]
Hi,

I'm trying to implement an FFT analysis using the Sound library on a Raspberry Pi and it seems that support for ARM devices has not been added yet.

Has anyone ever compiled this for ARM?

Thanks.

**Comment by gohai** [comment]
This is about to get addressed with #103

**Comment by tylergumb** [comment]
Sorry was this resolved?

I am still encountering error message that sound library is only available on 64-bit versions of processing when trying to run it on a rasberry pi 3.

I have tried using all versions of processing for linux available here:
https://processing.org/download/

Thanks.

**Comment by gohai** [comment]
@posivibez Support for ARM machines has been added to the source tree, but it has yet to be included in a proper release (the most recent one is from April 2016).

There is an experimental build you can download [here](https://github.com/processing/processing/wiki/Supported-Platforms#library-processing-sound).

**Comment by tylergumb** [comment]
@gohai thank you so much for the help

it is working when i test it. I am getting the below error, do you by any chance what may be causing this?

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (default), No such file or directory.

**Comment by gohai** [comment]
If it is working regardless this can be safely ignored for now.

**Comment by tylergumb** [comment]
cool thanks! @gohai

**Comment by tylergumb** [comment]
I'm trying to set this project up with an rasberry pi (so it can be self contained)
we were previously using a laptop:
https://vimeo.com/191306219

There are five audio tracks running simultaneously and the sand on the acrylic is triggering light sensors which change the playback rate of the tracks.
On the laptop as you can hear in the video the audio plays back smooth.
When I am testing it now on the pi with the same code it will cause cracks and some distortion in the sound, especially when changing the rate of 2 or more tracks simultaneously.

Do you by any chance know if this may be due to the sound library support of ARM being incomplete at the moment, or could it be a hardware issue that the sound hardware on the rasberry pi 3 is not capable of that number of simultaneous tracks being played back and the rate change and that's causing the distortion?

Any thoughts would be super appreciated.

Thanks so much for all the help.

**Comment by gohai** [comment]
@posivibez Sorry, this is really not the place for individual tech support...

FYI: The Pi doesn't even have a proper sound card, but uses a PWM channel from the main SOC to synthesize wave forms. I can't say what the limitations are on this one, but I wouldn't be surprised it performs worse than a laptop costing upwards of 10x as much.
